import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/Provider/AuthProvider";
import Navbar from "@/Components/Navbar";
import {NextUIProvider} from "@nextui-org/react"; 


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CryptoLens",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
               <NextUIProvider>
        <AuthProvider>
          <Navbar></Navbar>
         <div> {children}</div>
        </AuthProvider>
        </NextUIProvider>
      </body>

    </html>
  );
}
